[package]
name = "cassandra-messaging"
description = "Inter-node messaging protocol, connection management, verb handlers"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cassandra-common = { path = "../cassandra-common" }
bytes = { workspace = true }
byteorder = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
crossbeam = { workspace = true }
futures-util = { workspace = true }
thiserror = { workspace = true }
tokio-rustls.workspace = true
rustls-pki-types = "1.14.0"
rustls.workspace = true
cassandra-security = { version = "0.1.0", path = "../cassandra-security" }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
